### PR TITLE
Finished Assignment1

### PR DESCRIPTION
**Pull request by alexiapop**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
The rest of your code is nice and clean from what I see.
Most important thing is to split that controller which clearly is not adhering to the "single responsibility" principle and break it down into multiple controllers.

**Comment by alexiapop** [comment]
Thank you for the feedback! M-am gandit la asta and tried to do so , but had some issues with it .O sa incerc sa aplic mai bine pe urmatoarele assignmenturi .

**Comment by Alex-Cosma** [comment]
> Thank you for the feedback! M-am gandit la asta and tried to do so , but had some issues with it .O sa incerc sa aplic mai bine pe urmatoarele assignmenturi .

You still have some time

**Review by Alex-Cosma — COMMENTED** [review]
Excellent!

**Comment by Alex-Cosma** [comment]
Aș prefera să nu-i dai close, vreau să le dau merge

**Pull request closed without merging**
